[package]
name = "loxjit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.9.4"
num_enum = "0.5.7"
once_cell = "1.16.0"
replace_with = "0.1.7"
rustc-hash = "1.1.0"
utf8-chars = "2.0.3"
